### ISSUE TITLE
Crash on dismissing campaign modal second time

### ISSUE THREAD

**Issue by jaapmengers** [usabilla/usabilla-u4a-ios-swift-sdk#175]
The following scenario reliably results in a crash:

1. Send an event to trigger a campaign.
1. Click cancel, thus dismissing the campaign modal.
1. Reset the campaign data in order for the campaign modal to be shown a second time.
1. Again send the event.
1. Again click cancel.
1. The app now crashes.

![usabillacrash](https://user-images.githubusercontent.com/4312892/69622840-066e4f80-1042-11ea-86f4-731de2109c18.gif)

I've reproduced this scenario in an empty iOS project with a minimal Usabilla setup: [UsabillaCrash.zip](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/files/3891407/UsabillaCrash.zip)

The error seems to arise in 
```
Usabilla.CampaignViewController.introViewDidCancel(introView: Usabilla.UBIntroOutroView) ->
Usabilla.CampaignViewController.closeCampaign(atPageIndex: Swift.Optional<Swift.Int>) -> 
UIView.removeFromSuperView
```
In our crash reporting we also see references to `NSLayoutConstraintIsPotentiallyDanglyInContainer` which leads me to [this SO answer](https://stackoverflow.com/questions/53059578/application-crash-on-ios12-0-1-when-view-remove-from-super) 

Reproduced on iPhone 11 Pro Max simulator running iOS 13.2.2

**Comment by andreaiori** [comment]
Hi @jaapmengers , 
Thank you for reaching out. 
Sorry to hear you're having problems with our SDK but I'm here to help. 

The product team is already aware of the bug and it's working on a fix as we speak. 
I'll make sure to keep you updated but most probably the fix will be added with the next December release. 

In the meantime, please don't hesitate to ask if there is anything else.

**Comment by keshcreations** [comment]
Hi @jaapmengers,

Just a heads up from our side, this issue has been fixed in the [latest release of our SDK](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases). If you haven't already, please update to our latest SDK version and you should be able to take advantage of the fix.

Have a great day!

**Comment by jaapmengers** [comment]
Hi @keshcreations, thanks for the update. We actually use the usabilla-u4a-react-native package which is still on the 6.4.3 release of usabilla-u4a-ios-swift-sdk. We will update as soon as a new release is available there. Thanks for the help!

**Comment by keshcreations** [comment]
Hi @jaapmengers, 

Thanks for getting back to me on this. Which version of the React Native package are you using right now? In the latest version of the [React Native package (0.10.1)](https://github.com/usabilla/usabilla-u4a-react-native/releases), we have added the 'auto-linking' feature. This allows you to update to the latest version of the iOS SDK yourself. The steps that are required for this can be found in [our documentation](https://github.com/usabilla/usabilla-u4a-react-native#installation).

I hope this helps!

**Comment by jaapmengers** [comment]
@keshcreations Ah yes I see :) Thanks, I'm going to upgrade!

**Comment by AymenHARRATH** [comment]
Hello,

@jaapmengers , did the update fixed your crash?

@keshcreations I am having the same issue on my app. Even on the example that @jaapmengers made, after updating to the latest version of your SDK (6.4.7), the crash still occurs.

Reproduced on multiple iOS simulators and devices.

**Comment by jaapmengers** [comment]
@AymenHARRATH I think I got focussed on updating the SDK and forgot to check whether the issue persists. I didn't retry, but if you can reproduce it, it seems that the issue is still there.

We don't actually run into this problem in production. We only sometimes manually reset campaign data in debug versions of our app, so this is not a high prio issue for us.

**Comment by sverner23** [comment]
I am encountering this issue on production.  On the iOS Usabilla SDK (pod 'Usabilla', '~> 6.4.7') if you have two campaigns trigger in the same session and you dismiss both of them then the app crashes on the second dismiss in production. This is a significant blocker for us and is causing us to look at other vendors.  Please let me know when there is a fix
