### ISSUE TITLE
[Swift 3.0] Issues with UsabillaThemeConfigurator

### ISSUE THREAD

**Issue by ushafiq** [usabilla/usabilla-u4a-ios-swift-sdk#19]
- **Usabilla SDK version 3.0.0**
- **Swift version 3.0**
- **Xcode 8.1 Sierra**
---
I am seeing bugs in theme UsabillaThemeConfigurator, somehow it does not take into account custom text colours. Can you please fix this?

Please take a look at navigation bar styling, `Cancel` and `Submit` button texts are also orange.
[Usabilla feedback Form](http://imgur.com/a/Yu7O7)

My configurations (in swift 3.0)
```swift

func showFeedbackForm() {
        UsabillaFeedbackForm.delegate = self
        UsabillaFeedbackForm.showCancelButton = true
        UsabillaFeedbackForm.localizedStringFile = "Localizable"
        UsabillaFeedbackForm.loadFeedbackForm(getFeedbackFormID(), screenshot: nil, customVariables: nil, themeConfig: setupUsabillaTheme())
    }
    
    func setupUsabillaTheme() -> UsabillaThemeConfigurator{
        
        let configurator =  UsabillaThemeConfigurator()
        configurator.customFont = UIFont(name: "NotoSans", size: 18)
        
        configurator.titleColor = TNTColor.brandOrange.color()
        configurator.textColor = TNTColor.darkFont.color()
        configurator.accentColor = TNTColor.brandOrange.color()
        configurator.textOnAccentColor = UIColor.white
        configurator.textOnAccentColor = UIColor.white
        configurator.errorColor = UIColor.red

        configurator.statusBarColor = UIStatusBarStyle.lightContent
        
        return configurator
    }
```

---
Thanks,
Sem

**Comment by gPinato** [comment]
It seems to work fine for me.
With this configuration
```
   configurator =  UsabillaThemeConfigurator()
        //configurator.customFont = UIFont(name: "NotoSans", size: 18)
        
        configurator.titleColor = UIColor.orange
        configurator.textColor = UIColor.black
        configurator.accentColor = UIColor.orange
        configurator.textOnAccentColor = UIColor.blue
        configurator.errorColor = UIColor.red
        
        configurator.statusBarColor = UIStatusBarStyle.lightContent

```
 I get the two buttons in blue.

Are you sure it's not the text of the two buttons that it's empty and therefore we don't see anything?

**Comment by injectios** [comment]
Your code on iPad doesn't affect on navigation bar at all, it's still blue with white buttons, please fix

```
   // UI customization
        let configurator =  UsabillaThemeConfigurator()
        configurator.titleColor = UIColor.orange
        configurator.textColor = UIColor.black
        configurator.accentColor = UIColor.orange
        configurator.textOnAccentColor = UIColor.blue
        configurator.errorColor = UIColor.red
        configurator.statusBarColor = UIStatusBarStyle.lightContent
        
        let image = UsabillaFeedbackForm.takeScreenshot(self.view)
        UsabillaFeedbackForm.showCancelButton = true
        UsabillaFeedbackForm.delegate = self
        UsabillaFeedbackForm.loadFeedbackForm("xxx", screenshot: image, customVariables: nil, themeConfig: configurator)
```

**Comment by ushafiq** [comment]
Hi gPinato,

My bad, in my project there is a line of code which overrides navigation bar button color via appearance method. By remove that it is fixed now.

Thanks again for your response,
Sem

**Comment by gPinato** [comment]
@injectios The code works fine for me. There are a few things that might explain it.

First, does the form have the correct colors on an iphone?

The colors set in the web app override the colors set in the SDK.  Make sure the colors there are the right one and try again.

If this does not solve the problem, please specify ios version and ipad model where you see the problem.
