### ISSUE TITLE
Xcode 13 and iOS 15 findings

### ISSUE THREAD

**Issue by lennardtastic** [usabilla/usabilla-u4a-ios-swift-sdk#227]
Hi All,

I hope you all are enjoying WWDC (or if you're reading this later have enjoyed WWDC). With the beta releases of Xcode 13 and iOS 15, we've started testing to ensure that the SDK is ready as soon as possible. Since our SDK has Module Stability the SDK is already working with iOS 15. However, to make sure that we have all bases covered we would like to ask you to report any bugs/issues/findings that you find while using the SDK with iOS 15 and Xcode 13 under this issue.

Template for reports
```
- Issue Summary
- Xcode Version
- Xcode Release
- Xcode Build
- iOS Version
- iOS Release
- iOS Device used for testing
- Usabilla SDK Version
- Usabilla Feature Affected
- Hardware used (M1?)
```

**Comment by JackoPlane** [comment]
*Issue Summary*: Xcode 13's built-in SPM fails to resolve the Usabilla package
*Xcode Version*: 13.0, `13A5154h`
*Usabilla SDK Version*: `master` branch
*Hardware used*: Both x86 and M1 hardware

**Comment by gevartosky** [comment]
- Issue Summary: Xcode 13's error "unknown binary artifact extension 'dSYMs'" when trying to add the package
- Xcode Version: 13
- Xcode Release: 13A5154h
- Usabilla SDK Version: 6.8.1
- Hardware used (M1?): M1 Mac Mini
![image](https://user-images.githubusercontent.com/5980943/121601312-285cd680-ca1c-11eb-8910-2b41e9ff36fc.png)

**Comment by donnywdavis** [comment]
Just trying out Xcode 13 beta 2 and I am also having the same issue with resolving the package.

<img width="1179" alt="Untitled" src="https://user-images.githubusercontent.com/2036378/123463399-c4293d80-d5eb-11eb-992a-c91faff9fce7.png">

I have also seen the error mentioned above `unknown binary artifact extension 'dSYMs` when trying to resolve package dependencies.

**Comment by Nonnus** [comment]
- Issue Summary
Cannot resolve Usabilla SPM package
- Xcode Version
13 beta 2
- Usabilla SDK Version
6.8.2
- Usabilla Feature Affected
SPM resolving
- Hardware used
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
2,3 GHz Quad-Core Intel Core i7


is there any update on this topic? 
last comment was 24 days ago, we have a new Xcode 13 beta and issue is still present

I can see that when package is resolved it creates a `Usabilla.dsyms` folder in `DerivedData/.../SourcePackages/artifacts/Usabilla`, this is wrong as the xcframework should already include all required dsyms

**Comment by eduakaszas** [comment]
Hi @Nonnus, 

Thank you for your message & all the details.

Our developers are still looking into this. They'll provide a pre-release as soon as they have a working package under xCode 13 - Beta. 

Let us know if you have any questions in the meantime. 

Kind regards, 
Édua

**Comment by Nonnus** [comment]
any updates on this topic? 23 says have passed since your last comment and nothing changed, usabilla is still not resolving on latest xcode beta...

**Comment by andlie** [comment]
We have released version 6.8.4 last week, that should have resolve the Xcode 15 issue as well as the iOS 13 issue. Please let us know if You are still haveing the same problems.
We are keeping this thread open, should we find further issues during Apples releases of Betas for Xcode 15. Once the final version has been released, we will close this thread

**Comment by danlages** [comment]
- Issue Summary
 The usabila Navigation bar is displayed as transparent.
[Some Investigation have determined that the](https://developer.apple.com/forums/thread/682432) UINavigationBarAppearence Plays more of a roll with iOS 15 and scrollEdgeAppearence and Standard Appearance must have the same setting. 
Implementing this, however, has not resolved this issue. We configure colours within the dashboard so it could be some behaviour there? Let me know if you have any further questions. 

- Xcode Version
   Xcode 13 
- Xcode Release
   Beta 5
- Xcode Build
    13A5212g
- iOS Version
   15
- iOS Release
   Beta
- iOS Device used for testing
   Multiple (12 pro max, 11, 11 pro)
- Usabilla SDK Version
   '6.8.1'
- Usabilla Feature Affected
  - Form Presentation 
- Hardware used (M1?)
   Intel 15" mac  and test devices.

**Comment by eduakaszas** [comment]
Hi @danlages,

Thank you for your message. 

To investigate further, could you please also share the following information:
- screenshot of the issue
- form ID 
- app ID
- Campaign ID

Instead of sharing the above here, you can also send through these details to our support team at support@usabilla.com, if you'd like. 

Looking forward to hearing from you. 

Kind regards, 
Édus

**Comment by eduakaszas** [comment]
Hi @danlages,

Just to add to the above - could you also try doing a test on v6.8.4 using a non-M1 build? 

We currently don't have M1 build for v6.8.4 yet - we did a pre-release for v6.8.0 recently. Soon we will have a M1 builds ready for xCode 13 & iOS 15.

Looking forward to hearing from you. 

Kind regards,
Édua

**Comment by danlages** [comment]
Hey @eduakaszas,

Thank you for the quick response. 
Here is the screenshot: 

![Screenshot 2021-08-25 at 10 37 00](https://user-images.githubusercontent.com/18531016/131814045-ef06b3f7-a361-4710-8955-24950bd5d56f.png)

I will share the rest via the email you have provided to be safe. 

I can confirm that this has been tested on a non M1 mac with the app using both 6.8.1 and 6.84 version of Usabilla. 

Thank you
Dan

**Comment by eduakaszas** [comment]
Hi @danlages , 

Thank you for the additional details! Very helpful. 

Have you sent us the appID/formID etc. via email with us already? We've been monitoring the queue but haven't seen it yet so just wanted to confirm. 

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by danlages** [comment]
> Hi @danlages ,
> 
> Thank you for the additional details! Very helpful.
> 
> Have you sent us the appID/formID etc. via email with us already? We've been monitoring the queue but haven't seen it yet so just wanted to confirm.
> 
> Looking forward to hearing from you.
> 
> Kind regards,
> Édua

Hi @eduakaszas 

I have just sent it over. 

Thank you,

Dan

**Comment by eduakaszas** [comment]
Hi @danlages ,

Thank you - we've received the message!

We'll get back to you in this thread as soon as possible after our developers looked into this. We did fix this with _UINavigationbarAppearence_ for iOS 15, however, we'll look into why this is happening for you on v6.8.4.

Let us know if you have any questions in the meantime. 

Kind regards, 
Édua

**Comment by danlages** [comment]
> Hi @danlages ,
> 
> Thank you - we've received the message!
> 
> We'll get back to you in this thread as soon as possible after our developers looked into this. We did fix this with _UINavigationbarAppearence_ for iOS 15, however, we'll look into why this is happening for you on v6.8.4.
> 
> Let us know if you have any questions in the meantime.
> 
> Kind regards,
> Édua

Hey @eduakaszas, thanks for taking a look at this.

Are there any updates? 

Dan

**Comment by dbell-survey** [comment]
Hi Dan, 

Thank you for following up with us.  Our developers downloaded the latest beta for iOS 15 and did some testing and everything worked smoothly.  Because of this would it be possible for you to try to clear the project build (prod / carthage) cache and use the latest SDK 6.84 to try to see if you are able to produce the issue again? 

Thanks so much and I look forward to your reply.

**Comment by danlages** [comment]
hi @dbell-survey Okay, I will look into that today

**Comment by danlages** [comment]
> Hi Dan,
> 
> Thank you for following up with us. Our developers downloaded the latest beta for iOS 15 and did some testing and everything worked smoothly. Because of this would it be possible for you to try to clear the project build (pods / carthage) cache and use the latest SDK 6.8.4 to try to see if you are able to produce the issue again?
> 
> Thanks so much and I look forward to your reply.

Hi @dbell-survey I have updated to the latest version after clearing the pods and we are still seeing the issue. 
I have configure the navigation bar appearance in line with suggestions on apple forums but this still has no impact. It seems to me that this is a consequence of the colours coming from the dashboard. Do you have any further suggestions?

**Comment by danlages** [comment]
Hey @dbell-survey @eduakaszas 
I have tested this on a real device with the iOS 15 release candidate version and all looks fine. However, testing on the release candidate on the simulator (xcode 13) still shows the same issue.

**Comment by dbell-survey** [comment]
Hi Dan, 

Thank you for the update and I am sorry to hear that this is still not working for you. 

We do have some good news though, our developers will be releasing a new build with xcode13 release candidate this week which will fix this issue. I will follow up then once this has been released. 

In the meantime, if you have any additional questions, please do not hesitate to reach out.

**Comment by danlages** [comment]
hey @dbell-survey @eduakaszas, it looks like you latest release 6.8.5 has regressed this.

**Comment by gfb-digital-support** [comment]
Hi there, it looks like you emailed our billing or support teams directly. As a first step, please try our Help Center. We have expertly created articles with step by step instructions, videos, and wisdom to help you find a solution. Here's the link: https://help.surveymonkey.com

If you don't find what you're looking for, there's a Contact Us button at the bottom of each page. You can write to us directly so we can pull up your account and dig in. If you don't have an account, or can't log in, that's okay! Select "Continue as Guest" and our experts will get back to you as soon as they can.

NOTE: This is an automatic reply. Your email was not delivered to support but you can contact us using our Help Center.

ref:_00D301HuKJ._5004V19rMdT:ref autoresponse-identity

**Comment by WRiferreiro** [comment]
Hi @eduakaszas, we are using the latest version of the SDK (v6.11.0) and there still seems to be an issue with the header, that might have been introduced while fixing it for iOS 15.

As you can see on the picture below, the same camping looks different on iOS 15 and iOS 14. Is this something you are aware of?

![image](https://user-images.githubusercontent.com/97174115/151995953-d6a042a2-36a4-4637-8279-8b0f4f79b3dd.png)
